import re

# 1. Update Home Screen text
with open('lib/presentation/screens/home/home_screen.dart', 'r') as f:
    content = f.read()

content = content.replace(
    "UiText.t(context, 'Video Tutorials'),\n        UiText.t(context, 'YouTube Links'),",
    "UiText.t(context, 'Find Videos on YouTube'),\n        UiText.t(context, 'Search YouTube'),"
)

with open('lib/presentation/screens/home/home_screen.dart', 'w') as f:
    f.write(content)


# 2. Update Videos Screen AppBar and add disclaimer
with open('lib/presentation/screens/videos/videos_screen.dart', 'r') as f:
    v_content = f.read()

# Change App bar
v_content = v_content.replace(
    "title: Text(AppLocalizations.of(context).t('videoTutorialLinks'))",
    "title: Text(UiText.t(context, 'Find Videos on YouTube'))"
)

# Add disclaimer above the list
old_list = """          Expanded(
            child: ListView.builder("""

new_list = """          Container(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            color: isDark ? const Color(0xFF1E293B) : const Color(0xFFFFFBEB),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.info_outline, size: 18, color: AppTheme.accentOrange),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    UiText.t(context, 'These results open external YouTube searches. They are generated by YouTube, hosted externally, and are not officially reviewed or controlled by this app. Always verify safety practices.'),
                    style: TextStyle(
                      fontSize: 12,
                      color: isDark ? Colors.white70 : Colors.black87,
                      height: 1.3,
                    ),
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: ListView.builder("""

v_content = v_content.replace(old_list, new_list)

with open('lib/presentation/screens/videos/videos_screen.dart', 'w') as f:
    f.write(v_content)

print("Updated video section")
