import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/localization/ui_text.dart';
import '../../../core/localization/localized_content.dart';
import '../../../data/repositories/app_repository.dart';
import '../../../models/tutorial_video.dart';
import '../calculators/calculator_detail_screen.dart';
import '../standards/pakistan_standards_screen.dart';
import '../theory/article_detail_screen.dart';
import '../wiring/diagram_detail_screen.dart';

class VideosScreen extends StatefulWidget {
  const VideosScreen({super.key});

  @override
  State<VideosScreen> createState() => _VideosScreenState();
}

class _VideosScreenState extends State<VideosScreen> {
  String _selectedCategory = 'all';
  String _searchQuery = '';

  List<TutorialVideo> get filteredVideos {
    var videos = AppRepository.tutorialVideos;
    if (_selectedCategory != 'all') {
      videos = videos
          .where((video) => video.category == _selectedCategory)
          .toList();
    }
    if (_searchQuery.isNotEmpty) {
      final query = _searchQuery.toLowerCase().trim();
      videos = videos
          .where((video) => video.searchableText.contains(query))
          .toList();
    }
    return videos;
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Scaffold(
      appBar: AppBar(title: Text(UiText.t(context, 'Video Tutorial Links'))),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 4),
            child: TextField(
              onChanged: (value) => setState(() => _searchQuery = value),
              decoration: InputDecoration(
                hintText: UiText.t(context, 'Search tutorial links, topics...'),
                prefixIcon: const Icon(Icons.search),
                suffixIcon: _searchQuery.isNotEmpty
                    ? IconButton(
                        icon: const Icon(Icons.clear),
                        onPressed: () => setState(() => _searchQuery = ''),
                      )
                    : null,
              ),
            ),
          ),
          SizedBox(
            height: 50,
            child: ListView(
              scrollDirection: Axis.horizontal,
              padding: const EdgeInsets.symmetric(horizontal: 16),
              children: [
                _CategoryChip(
                  label: UiText.t(context, 'All'),
                  isSelected: _selectedCategory == 'all',
                  onTap: () => setState(() => _selectedCategory = 'all'),
                ),
                ...AppRepository.videoCategories.map(
                  (category) => _CategoryChip(
                    label: UiText.t(context, category.name),
                    isSelected: _selectedCategory == category.id,
                    color: Color(
                      int.parse(category.colorHex.replaceFirst('#', '0xFF')),
                    ),
                    onTap: () =>
                        setState(() => _selectedCategory = category.id),
                  ),
                ),
              ],
            ),
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            color: isDark ? const Color(0xFF1E293B) : const Color(0xFFFFFBEB),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.info_outline, size: 18, color: AppTheme.accentOrange),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    UiText.t(context, 'These results open external YouTube searches. They are generated by YouTube, hosted externally, and are not officially reviewed or controlled by this app. Always verify safety practices.'),
                    style: TextStyle(
                      fontSize: 12,
                      color: isDark ? Colors.white70 : Colors.black87,
                      height: 1.3,
                    ),
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
              itemCount: filteredVideos.length,
              itemBuilder: (context, index) {
                final video = filteredVideos[index];
                final category = AppRepository.videoCategories.firstWhere(
                  (c) => c.id == video.category,
                );
                final color = Color(
                  int.parse(category.colorHex.replaceFirst('#', '0xFF')),
                );
                return GestureDetector(
                  onTap: () => Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => VideoDetailScreen(video: video),
                    ),
                  ),
                  child: Container(
                    margin: const EdgeInsets.only(bottom: 12),
                    padding: const EdgeInsets.all(14),
                    decoration: BoxDecoration(
                      color: Theme.of(context).cardTheme.color,
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(
                        color: isDark
                            ? const Color(0xFF334155)
                            : const Color(0xFFE2E8F0),
                      ),
                    ),
                    child: Row(
                      children: [
                        _VideoThumb(
                          color: color,
                          icon: _getIconData(category.iconName),
                        ),
                        const SizedBox(width: 14),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                LocalizedContent.text(context, video.title),
                                maxLines: 1,
                                overflow: TextOverflow.ellipsis,
                                style: const TextStyle(
                                  fontWeight: FontWeight.w700,
                                ),
                              ),
                              const SizedBox(height: 5),
                              Text(
                                LocalizedContent.text(
                                  context,
                                  video.description,
                                ),
                                maxLines: 2,
                                overflow: TextOverflow.ellipsis,
                                style: Theme.of(context).textTheme.bodySmall,
                              ),
                              const SizedBox(height: 8),
                              Wrap(
                                spacing: 6,
                                runSpacing: 4,
                                children: [
                                  _MiniBadge(
                                    LocalizedContent.quizDifficulty(
                                      context,
                                      video.difficulty,
                                    ),
                                    color,
                                  ),
                                  _MiniBadge(
                                    LocalizedContent.text(
                                      context,
                                      category.name,
                                    ),
                                    color,
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 8),
                        const Icon(
                          Icons.arrow_forward_ios,
                          size: 16,
                          color: Color(0xFF94A3B8),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  IconData _getIconData(String name) {
    switch (name) {
      case 'health_and_safety':
        return Icons.health_and_safety;
      case 'account_tree':
        return Icons.account_tree;
      case 'calculate':
        return Icons.calculate;
      case 'wb_sunny':
        return Icons.wb_sunny;
      case 'gavel':
        return Icons.gavel;
      default:
        return Icons.play_circle_fill;
    }
  }
}

class VideoDetailScreen extends StatelessWidget {
  final TutorialVideo video;
  const VideoDetailScreen({super.key, required this.video});

  Future<void> _openVideo(BuildContext context) async {
    final uri = Uri.parse(video.youtubeUrl);
    try {
      final launched = await launchUrl(
        uri,
        mode: LaunchMode.externalApplication,
      );
      if (!launched && context.mounted) _showOpenError(context);
    } catch (_) {
      if (context.mounted) _showOpenError(context);
    }
  }

  void _showOpenError(BuildContext context) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(
          UiText.t(
            context,
            'Could not open YouTube. Check internet connection or browser app.',
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final category = AppRepository.videoCategories.firstWhere(
      (c) => c.id == video.category,
    );
    final color = Color(int.parse(category.colorHex.replaceFirst('#', '0xFF')));

    return Scaffold(
      appBar: AppBar(title: Text(LocalizedContent.text(context, video.title))),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _TutorialLinkHeader(
              video: video,
              category: category,
              color: color,
              isDark: isDark,
            ),
            const SizedBox(height: 18),
            Text(
              LocalizedContent.text(context, video.description),
              style: Theme.of(
                context,
              ).textTheme.bodyLarge?.copyWith(height: 1.55),
            ),
            const SizedBox(height: 14),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                _MiniBadge(
                  LocalizedContent.text(context, category.name),
                  color,
                ),
                _MiniBadge(
                  LocalizedContent.quizDifficulty(context, video.difficulty),
                  color,
                ),
                ...video.tags
                    .take(4)
                    .map(
                      (tag) => _MiniBadge(
                        LocalizedContent.text(context, tag),
                        color,
                      ),
                    ),
              ],
            ),
            const SizedBox(height: 22),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: () => _openVideo(context),
                icon: const Icon(Icons.open_in_new),
                label: Text(UiText.t(context, 'Watch on YouTube')),
                style: ElevatedButton.styleFrom(
                  backgroundColor: color,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  textStyle: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
            ),
            const SizedBox(height: 24),
            Text(
              UiText.t(context, 'Related App Content'),
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700),
            ),
            const SizedBox(height: 10),
            ..._relatedTiles(context),
            const SizedBox(height: 24),
          ],
        ),
      ),
    );
  }

  List<Widget> _relatedTiles(BuildContext context) {
    final widgets = <Widget>[];
    if (video.relatedArticleId != null) {
      final matches = AppRepository.theoryArticles
          .where((a) => a.id == video.relatedArticleId)
          .toList();
      if (matches.isNotEmpty) {
        widgets.add(
          _RelatedTile(
            icon: Icons.menu_book,
            title: LocalizedContent.articleTitle(context, matches.first),
            subtitle: UiText.t(context, 'Theory article'),
            onTap: () => Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => ArticleDetailScreen(article: matches.first),
              ),
            ),
          ),
        );
      }
    }
    if (video.relatedCalculatorId != null) {
      final matches = AppRepository.calculators
          .where((c) => c.id == video.relatedCalculatorId)
          .toList();
      if (matches.isNotEmpty) {
        widgets.add(
          _RelatedTile(
            icon: Icons.calculate,
            title: LocalizedContent.calculatorName(context, matches.first),
            subtitle: UiText.t(context, 'Calculator'),
            onTap: () => Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) =>
                    CalculatorDetailScreen(calculator: matches.first),
              ),
            ),
          ),
        );
      }
    }
    if (video.relatedDiagramId != null) {
      final matches = AppRepository.wiringDiagrams
          .where((d) => d.id == video.relatedDiagramId)
          .toList();
      if (matches.isNotEmpty) {
        widgets.add(
          _RelatedTile(
            icon: Icons.account_tree,
            title: LocalizedContent.wiringTitle(context, matches.first),
            subtitle: UiText.t(context, 'Wiring diagram'),
            onTap: () => Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => DiagramDetailScreen(diagram: matches.first),
              ),
            ),
          ),
        );
      }
    }
    if (video.relatedStandardId != null) {
      final matches = AppRepository.pakistanStandards
          .where((s) => s.id == video.relatedStandardId)
          .toList();
      if (matches.isNotEmpty) {
        widgets.add(
          _RelatedTile(
            icon: Icons.gavel,
            title: LocalizedContent.standardTitle(context, matches.first),
            subtitle: UiText.t(context, 'Standards & Codes note'),
            onTap: () => Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) =>
                    PakistanStandardDetailScreen(standard: matches.first),
              ),
            ),
          ),
        );
      }
    }
    if (widgets.isEmpty)
      widgets.add(Text(UiText.t(context, 'No related content linked yet.')));
    return widgets;
  }
}

class _TutorialLinkHeader extends StatelessWidget {
  final TutorialVideo video;
  final VideoCategory category;
  final Color color;
  final bool isDark;

  const _TutorialLinkHeader({
    required this.video,
    required this.category,
    required this.color,
    required this.isDark,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: Theme.of(context).cardTheme.color,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(
          color: isDark ? const Color(0xFF334155) : const Color(0xFFE2E8F0),
        ),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  LocalizedContent.text(context, video.title),
                  style: const TextStyle(
                    fontSize: 20,
                    fontWeight: FontWeight.w700,
                    height: 1.18,
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  '${LocalizedContent.text(context, category.name)} • '
                  '${LocalizedContent.quizDifficulty(context, video.difficulty)}',
                  style: Theme.of(
                    context,
                  ).textTheme.bodySmall?.copyWith(fontWeight: FontWeight.w700),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _VideoThumb extends StatelessWidget {
  final Color color;
  final IconData icon;
  const _VideoThumb({required this.color, required this.icon});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 72,
      height: 72,
      decoration: BoxDecoration(
        color: color.withOpacity(0.12),
        borderRadius: BorderRadius.circular(16),
      ),
      child: Stack(
        alignment: Alignment.center,
        children: [
          Icon(icon, color: color, size: 30),
          Positioned(
            right: 8,
            bottom: 8,
            child: Icon(Icons.play_circle_fill, color: color, size: 20),
          ),
        ],
      ),
    );
  }
}

class _MiniBadge extends StatelessWidget {
  final String text;
  final Color color;
  const _MiniBadge(this.text, this.color);

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(7),
      ),
      child: Text(
        text,
        style: TextStyle(
          fontSize: 11,
          color: color,
          fontWeight: FontWeight.w700,
        ),
      ),
    );
  }
}

class _RelatedTile extends StatelessWidget {
  final IconData icon;
  final String title;
  final String subtitle;
  final VoidCallback onTap;
  const _RelatedTile({
    required this.icon,
    required this.title,
    required this.subtitle,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      decoration: BoxDecoration(
        color: Theme.of(context).cardTheme.color,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: isDark ? const Color(0xFF334155) : const Color(0xFFE2E8F0),
        ),
      ),
      child: ListTile(
        leading: Icon(icon, color: AppTheme.primaryBlue),
        title: Text(title, maxLines: 1, overflow: TextOverflow.ellipsis),
        subtitle: Text(subtitle),
        trailing: const Icon(Icons.arrow_forward_ios, size: 15),
        onTap: onTap,
      ),
    );
  }
}

class _CategoryChip extends StatelessWidget {
  final String label;
  final bool isSelected;
  final Color? color;
  final VoidCallback onTap;

  const _CategoryChip({
    required this.label,
    required this.isSelected,
    this.color,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final selectedColor = color ?? AppTheme.primaryBlue;
    return Padding(
      padding: const EdgeInsets.only(right: 8),
      child: GestureDetector(
        onTap: onTap,
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 200),
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
          decoration: BoxDecoration(
            color: isSelected ? selectedColor : Colors.transparent,
            borderRadius: BorderRadius.circular(24),
            border: Border.all(
              color: isSelected ? selectedColor : const Color(0xFFCBD5E1),
            ),
          ),
          child: Text(
            label,
            style: TextStyle(
              color: isSelected ? Colors.white : const Color(0xFF64748B),
              fontSize: 13,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
      ),
    );
  }
}
